declare const iconsFill: {
    allSlots: string;
    arrowBack: string;
    arrowNext: string;
    arrowUp: string;
    bankCard: string;
    calendar: string;
    check: string;
    checkCircle: string;
    closeCircle: string;
    close: string;
    deposit: string;
    dropdownDown: string;
    dropdownLeft: string;
    dropdownRight: string;
    dropdownUp: string;
    exclamationCircle: string;
    exclamationOctagon: string;
    exclamationTriangle: string;
    fullscreen: string;
    info1: string;
    info3: string;
    info4: string;
    promoCode: string;
    mail: string;
    phone: string;
    chat: string;
    minus: string;
    notAvailable: string;
    plus: string;
    prize: string;
    rollUp: string;
    safety2: string;
    timer: string;
    user: string;
    visibilityOff: string;
    visibilityOn: string;
    copy: string;
    radioButton: string;
    radioButtonActive: string;
    longTap: string;
    bitcoin: string;
    paymentCard: string;
    paymentCard2: string;
    filterOutline: string;
    edit: string;
    legality: string;
    withdraw: string;
};
declare const iconsNavigation: {
    pokies: string;
    bet: string;
    arena: string;
    table: string;
    eSport: string;
    bonuses: string;
    vip: string;
    profile: string;
    faq: string;
    giftShop: string;
    birthdayPromo: string;
    more: string;
};
declare const iconsOutline: {
    giftBox: string;
    notificationsOff: string;
    search: string;
    filters: string;
    support: string;
    loader: string;
    tournaments: string;
    actions: string;
    quests: string;
    current: string;
    vipEvents: string;
};
declare const iconsSocial: {
    facebook: string;
    instagram: string;
    twitter: string;
    whatsapp: string;
};
export type IconsFill = keyof typeof iconsFill;
export type IconsNavigation = keyof typeof iconsNavigation;
export type IconsOutline = keyof typeof iconsOutline;
export type IconsSocial = keyof typeof iconsSocial;
export type IconName = IconsFill | IconsNavigation | IconsOutline | IconsSocial;
export declare const icons: Record<string, string>;
export {};
