name: ci-linters

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    name: Run linters
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
      pull-requests: read
    strategy:
      matrix:
        os: [ubuntu-latest] # macos-latest, windows-latest
        node: [22.12.0]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      - name: Install pnpm
        uses: pnpm/action-setup@v4
      - name: Install dependencies
        run: pnpm install
      - name: Eslint
        run: pnpm lint:eslint
      - name: Prettier
        run: pnpm lint:prettier
      - name: Types check
        run: pnpm lint:tsc
